project_id = "gsgowetqzqeviqtxgofl"

[functions.fetch-stock-data]
verify_jwt = true

[functions.fetch-stock-news]
verify_jwt = true

[functions.scrape-stock-price]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true
